name: CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm ci --prefix server
      - run: npx prisma generate --prefix server || true
      - run: npm run lint --prefix server
      - run: npm run build --prefix server
      - run: npm test --prefix server


